version: '3.8'

services:
  postgres:
    image: postgres:14.6
    container_name: postgres-db
    environment:
      POSTGRES_DB: cloud_storage
      POSTGRES_USER: david
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U david -d cloud_storage" ]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001" # UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 5s
      timeout: 3s
      retries: 3

  app:
    build: .
    container_name: spring-app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      minio:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/cloud_storage
      SPRING_DATASOURCE_USERNAME: david
      SPRING_DATASOURCE_PASSWORD: password

      SPRING_FLYWAY_USER: david
      SPRING_FLYWAY_PASSWORD: password

    ports:
      - "8080:8080"

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  default:
    name: cloud-storage-net
    driver: bridge
